spring:
  application:
    name: eureka-server
  zipkin:
    #base-url: http://localhost:9411
    base-url: http://zipkin:9411

server:
  port: 8761

eureka:
  client:
    #false because this is our server itself
    fetch-registry: false
    register-with-eureka: false

